### PR TITLE
Support RISC-V

### PR DESCRIPTION
**Pull request by danc86**
Cherry-picked from lld master:
https://github.com/llvm-mirror/lld/commit/9e54d159934e86f7a83c58ed21341bc89ff2bd2b

Originally reviewed here:
https://reviews.llvm.org/D39322

### CODE REVIEW

**Comment by danc86** [comment]
Sorry I'm not sure if it makes sense to send PRs to this fork, but I thought I'd try...

This commit is the initial support for the RISCV architecture in lld. It landed in lld master recently, unfortunately after lld 7.0 was branched off.

LLVM itself supports RISCV in 7.0.0, and the first RISCV target landed in Rust itself not long ago, but work is still ongoing to fully support the architecture in lld. This initial patch is enough to link static binaries for the riscv32imac-unknown-none-elf embedded target, although it is still missing some features needed to link dynamic binaries for a Linux userland.

We would like to land this patch in rust-lld if possible because it greatly improves the user experience for people who are building for the new riscv32imac-unknown-none-elf target. Currently, they have to obtain a GNU cross toolchain from elsewhere in order to link their Rust programs. With this patch we will be able to switch the target to use rust-lld by default.

Corresponding changes to the linker script to support lld are in rust-embedded/riscv-rt#10.

**Comment by danc86** [comment]
Also in case it matters, I just wanted to clarify that I am *not* the original author of this patch nor am I involved in lld development. I've just been helping out in the Rust Embedded WG RISCV team.

**Comment by alexcrichton** [comment]
Sounds good to me, thanks!

Anything that backports an already-landed patch and doesn't regress our tests is good by our measure :)

**Comment by danc86** [comment]
Thanks for merging this @alexcrichton ! I guess the next step is a PR for rust-lang/rust to update the lld submodule to this commit, right? I will file that now.

**Comment by danc86** [comment]
rust-lang/rust#53492 is the corresponding PR to pull this commit into the submodule.

**Pull request merged**
